# TCL File Generated by Component Editor 13.0
# Tue Aug 23 11:14:28 CEST 2016
# DO NOT MODIFY


# 
# rsa_wrapper "rsa_wrapper" v1.0
#  2016.08.23.11:14:28
# 
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module rsa_wrapper
# 
set_module_property DESCRIPTION ""
set_module_property NAME rsa_wrapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME rsa_wrapper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rsa_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file rsa_wrapper.vhd VHDL PATH rsa_wrapper.vhd TOP_LEVEL_FILE
add_fileset_file modmult.vhd VHDL PATH modmult.vhd
add_fileset_file rsacypher.vhd VHDL PATH rsacypher.vhd


# 
# parameters
# 
add_parameter BITSIZE INTEGER 64
set_parameter_property BITSIZE DEFAULT_VALUE 64
set_parameter_property BITSIZE DISPLAY_NAME BITSIZE
set_parameter_property BITSIZE TYPE INTEGER
set_parameter_property BITSIZE UNITS None
set_parameter_property BITSIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITSIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point mm_params
# 
add_interface mm_params avalon end
set_interface_property mm_params addressUnits WORDS
set_interface_property mm_params associatedClock clock_sink
set_interface_property mm_params associatedReset reset_sink
set_interface_property mm_params bitsPerSymbol 8
set_interface_property mm_params burstOnBurstBoundariesOnly false
set_interface_property mm_params burstcountUnits WORDS
set_interface_property mm_params explicitAddressSpan 0
set_interface_property mm_params holdTime 0
set_interface_property mm_params linewrapBursts false
set_interface_property mm_params maximumPendingReadTransactions 0
set_interface_property mm_params readLatency 0
set_interface_property mm_params readWaitTime 1
set_interface_property mm_params setupTime 0
set_interface_property mm_params timingUnits Cycles
set_interface_property mm_params writeWaitTime 0
set_interface_property mm_params ENABLED true
set_interface_property mm_params EXPORT_OF ""
set_interface_property mm_params PORT_NAME_MAP ""
set_interface_property mm_params SVD_ADDRESS_GROUP ""

add_interface_port mm_params mm_params_address address Input 2
add_interface_port mm_params mm_params_read read Input 1
add_interface_port mm_params mm_params_write write Input 1
add_interface_port mm_params mm_params_readdata readdata Output 32
add_interface_port mm_params mm_params_writedata writedata Input 32
add_interface_port mm_params mm_params_waitrequest waitrequest Output 1
set_interface_assignment mm_params embeddedsw.configuration.isFlash 0
set_interface_assignment mm_params embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm_params embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm_params embeddedsw.configuration.isPrintableDevice 0


# 
# connection point input_stream
# 
add_interface input_stream avalon_streaming end
set_interface_property input_stream associatedClock clock_sink
set_interface_property input_stream associatedReset reset_sink
set_interface_property input_stream dataBitsPerSymbol 8
set_interface_property input_stream errorDescriptor ""
set_interface_property input_stream firstSymbolInHighOrderBits true
set_interface_property input_stream maxChannel 0
set_interface_property input_stream readyLatency 0
set_interface_property input_stream ENABLED true
set_interface_property input_stream EXPORT_OF ""
set_interface_property input_stream PORT_NAME_MAP ""
set_interface_property input_stream SVD_ADDRESS_GROUP ""

add_interface_port input_stream st_in_ready ready Output 1
add_interface_port input_stream st_in_valid valid Input 1
add_interface_port input_stream st_in_sop startofpacket Input 1
add_interface_port input_stream st_in_eop endofpacket Input 1
add_interface_port input_stream st_in_data data Input 32


# 
# connection point output_stream
# 
add_interface output_stream avalon_streaming start
set_interface_property output_stream associatedClock clock_sink
set_interface_property output_stream associatedReset reset_sink
set_interface_property output_stream dataBitsPerSymbol 8
set_interface_property output_stream errorDescriptor ""
set_interface_property output_stream firstSymbolInHighOrderBits true
set_interface_property output_stream maxChannel 0
set_interface_property output_stream readyLatency 0
set_interface_property output_stream ENABLED true
set_interface_property output_stream EXPORT_OF ""
set_interface_property output_stream PORT_NAME_MAP ""
set_interface_property output_stream SVD_ADDRESS_GROUP ""

add_interface_port output_stream st_out_data data Output 32
add_interface_port output_stream st_out_ready ready Input 1
add_interface_port output_stream st_out_valid valid Output 1
add_interface_port output_stream st_out_sop startofpacket Output 1
add_interface_port output_stream st_out_eop endofpacket Output 1
add_interface_port output_stream st_out_empty empty Output 2


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1

